<?php
session_start();
$products = [
 ['id'=>1,'name'=>'Cyclone TWS Pro নয়েজ ক্যানসেলিং ইয়ারবাডস','category'=>'TWS Audio','regular'=>1350,'price'=>850,'discount'=>35,'rating'=>'4.9','sales'=>185,'image'=>'src/assets/images/tws_earbuds_pro_1790972827406.jpg'],
 ['id'=>2,'name'=>'Cyclone Watch Ultra AMOLED ব্লুটুথ কলিং স্মার্টওয়াচ','category'=>'Smart Watch','regular'=>2150,'price'=>1290,'discount'=>40,'rating'=>'5.0','sales'=>212,'image'=>'src/assets/images/smartwatch_ultra_black_1790972839119.jpg'],
 ['id'=>3,'name'=>'Cyclone 20,000mAh 22.5W ফাস্ট চার্জিং পাওয়ার ব্যাংক','category'=>'Powerbank','regular'=>2150,'price'=>1550,'discount'=>28,'rating'=>'4.8','sales'=>140,'image'=>'src/assets/images/powerbank_fast_charge_1790972850858.jpg'],
 ['id'=>4,'name'=>'Cyclone Audio Max ওয়্যারলেস স্টুডিও হেডফোন','category'=>'Headphones','regular'=>2900,'price'=>1950,'discount'=>33,'rating'=>'4.9','sales'=>98,'image'=>'src/assets/images/hero_gadget_slider_1790972816745.jpg'],
 ['id'=>5,'name'=>'Cyclone Mini পকেট সাইজ আল্ট্রা-কম্প্যাক্ট TWS','category'=>'TWS Audio','regular'=>890,'price'=>690,'discount'=>22,'rating'=>'4.7','sales'=>76,'image'=>'src/assets/images/tws_earbuds_pro_1790972827406.jpg'],
 ['id'=>6,'name'=>'Cyclone 65W টাইপ-সি ব্রেডেড সুপার ফাস্ট চার্জিং ক্যাবল','category'=>'Accessories','regular'=>520,'price'=>290,'discount'=>45,'rating'=>'4.9','sales'=>350,'image'=>'src/assets/images/powerbank_fast_charge_1790972850858.jpg']
];
$cart = $_SESSION['cart'] ?? [];
if ($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['action'])) {
 $id=(int)($_POST['id']??0); $action=$_POST['action'];
 if ($action==='add') { $cart[$id]=($cart[$id]??0)+1; }
 if ($action==='remove' && isset($cart[$id])) { $cart[$id]--; if($cart[$id]<1) unset($cart[$id]); }
 $_SESSION['cart']=$cart; header('Location: index.php#products'); exit;
}
$cartCount=array_sum($cart); $cartTotal=0; foreach($cart as $id=>$qty){foreach($products as $p){if($p['id']==$id)$cartTotal+=$p['price']*$qty;}}
$filter=$_GET['category']??'all'; $search=trim($_GET['q']??'');
$visible=array_filter($products,fn($p)=>($filter==='all'||$p['category']===$filter)&&(!$search||mb_stripos($p['name'],$search)!==false));
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?><!doctype html><html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CycloneMart | অনলাইন শপিং বাংলাদেশ</title><link rel="stylesheet" href="styles.css"></head><body>
<div class="hotline">হটলাইন: <b>০১৭১২-৩৪৫৬৭৮</b> <span>সকাল ৯টা - রাত ১১টা</span><span>সারাদেশে ক্যাশ অন ডেলিভারি · ৭ দিনের রিটার্ন</span></div>
<header><a class="logo" href="index.php"><strong>C<span>M</span></strong><span>Cyclone<span class="red">Mart</span><small>অনলাইন শপিং বাংলাদেশ</small></span></a><form class="search"><input name="q" value="<?=e($search)?>" placeholder="পণ্যের নাম খুঁজুন (যেমন: TWS, Smart Watch)"><button>খুঁজুন</button></form><a class="cart" href="#cart">কার্ট <b><?= $cartCount ?></b><small>৳<?=number_format($cartTotal)?></small></a></header>
<nav><a class="active" href="index.php">হোম</a><a href="#products">সব পণ্য</a><a href="#why">কেন আমরা</a><a href="#footer">যোগাযোগ</a></nav>
<main><section class="hero"><div><p class="eyebrow">বাংলাদেশের বিশ্বস্ত গ্যাজেট শপ</p><h1>আপনার পছন্দের গ্যাজেট,<br><span>সেরা দামে</span></h1><p class="hero-copy">অরিজিনাল পণ্য, দ্রুত ডেলিভারি এবং ক্যাশ অন ডেলিভারি সুবিধা—সব এক জায়গায়।</p><a class="button" href="#products">শপিং শুরু করুন →</a></div><img src="src/assets/images/hero_gadget_slider_1790972816745.jpg" alt="Cyclone গ্যাজেট"></section>
<section class="trust" id="why"><div><b>৭ দিন</b><span>রিটার্ন পলিসি</span></div><div><b>সারা দেশ</b><span>ডেলিভারি সুবিধা</span></div><div><b>১০০%</b><span>অরিজিনাল পণ্য</span></div><div><b>২৪/৭</b><span>কাস্টমার সাপোর্ট</span></div></section>
<section class="shop" id="products"><aside><h3>ক্যাটাগরি</h3><?php $cats=['all'=>'সব পণ্য','TWS Audio'=>'TWS Audio','Smart Watch'=>'Smart Watch','Powerbank'=>'Powerbank','Headphones'=>'Headphones','Accessories'=>'Accessories']; foreach($cats as $key=>$label): ?><a class="<?= $filter===$key?'selected':'' ?>" href="?category=<?=urlencode($key)?>#products"><?=e($label)?></a><?php endforeach; ?></aside><div class="catalog"><div class="section-title"><div><p class="eyebrow">জনপ্রিয় কালেকশন</p><h2>ট্রেন্ডিং গ্যাজেট</h2></div><span><?=count($visible)?>টি পণ্য</span></div><div class="grid"><?php foreach($visible as $p): ?><article class="card"><div class="product-image"><span>-<?=$p['discount']?>%</span><img src="<?=e($p['image'])?>" alt="<?=e($p['name'])?>"></div><div class="card-body"><small><?=e($p['category'])?></small><h3><?=e($p['name'])?></h3><div class="rating">★ <?=$p['rating']?> <em>(<?=$p['sales']?> বিক্রি)</em></div><div class="price"><b>৳<?=number_format($p['price'])?></b><del>৳<?=number_format($p['regular'])?></del></div><div class="actions"><form method="post"><input type="hidden" name="action" value="add"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="add">কার্টে যোগ</button></form><button class="order" data-name="<?=e($p['name'])?>">অর্ডার করুন</button></div></div></article><?php endforeach; ?></div></div></section>
<section class="cart-panel" id="cart"><div><p class="eyebrow">আপনার নির্বাচন</p><h2>কার্ট ও অর্ডার</h2></div><?php if(!$cartCount): ?><p class="empty">আপনার কার্ট এখনো খালি। পছন্দের পণ্যে কার্টে যোগ করুন।</p><?php else: foreach($cart as $id=>$qty): foreach($products as $p) if($p['id']==$id): ?><div class="cart-row"><span><?=e($p['name'])?> × <?=$qty?></span><b>৳<?=number_format($p['price']*$qty)?></b><form method="post"><input type="hidden" name="action" value="remove"><input type="hidden" name="id" value="<?=$id?>"><button>−</button></form></div><?php endif; endforeach; endforeach; ?><div class="cart-total">সর্বমোট <b>৳<?=number_format($cartTotal)?> + ডেলিভারি</b></div><button class="button checkout">চেকআউট করুন</button><?php endif; ?></section></main>
<footer id="footer"><b>Cyclone<span>Mart</span></b><p>বিশ্বস্ত অনলাইন গ্যাজেট শপ · ঢাকা, বাংলাদেশ</p><p>© <?=date('Y')?> CycloneMart. সর্বস্বত্ব সংরক্ষিত।</p></footer><div class="toast" id="toast"></div><script>document.querySelectorAll('.order').forEach(b=>b.onclick=()=>{document.getElementById('toast').textContent='অর্ডার করতে কার্টে পণ্য যোগ করে চেকআউট করুন';document.getElementById('toast').classList.add('show');setTimeout(()=>document.getElementById('toast').classList.remove('show'),2800)});</script></body></html>
